######################################################################
# Automatically generated by qmake (2.01a) Sun May 11 07:16:03 2014
######################################################################

TEMPLATE = app
TARGET = easy-paint
DEPENDPATH += .
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += mainwindow.h scribblearea.h
SOURCES += main.cpp mainwindow.cpp scribblearea.cpp

CONFIG += static
