######################################################################
# Automatically generated by qmake (2.01a) Mon May 5 18:59:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h scribblearea.h
SOURCES += main.cpp mainwindow.cpp scribblearea.cpp
