######################################################################
# Automatically generated by qmake (2.01a) Sat May 10 15:54:14 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h scribblearea.h
SOURCES += main.cpp mainwindow.cpp scribblearea.cpp
